x-api-environment: &default-api-environment
  NODE_ENV: ${DK_ENVIRONMENT}
  API_PORT: ${API_PORT}
  API_DEBUG_PORT: ${API_DEBUG_PORT}
  DB_VERX_USER: ${DB_VERX_USER}
  DB_VERX_PASSWORD: ${DB_VERX_PASSWORD}
  DB_VERX_DATABASE: ${DB_VERX_DATABASE}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}

services:
  api:
    build:
      context: ./projects/api
      dockerfile: Dockerfile.${DK_ENVIRONMENT}
      args:
        DK_UID: ${DK_UID}
        DK_GID: ${DK_GID}
    container_name: ${DK_PROJECT_NAME}_api
    ports:
      - "${API_PORT}:${API_PORT}"
      - "${API_DEBUG_PORT}:${API_DEBUG_PORT}"
    environment: *default-api-environment
    volumes:
      - ${PWD}/projects/api:/home/node/project
    networks:
      - backend
    command: ["yarn", "start:dev"]

  postgres:
    build:
      context: ./docker/services/postgres
    container_name: ${DK_PROJECT_NAME}_postgres
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DATABASES: "${POSTGRES_DATABASES}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - backend

networks:
  backend:
    driver: bridge
